sudo: required

language: python

python:
  - 2.7
  - 3.6

services:
  - docker

before_install:
  - travis_wait script/up

script:
  - script/test

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      script/distribute;
    fi