version: '3'
services:
  tf-serving:
    build:
      context: docker/test-tf-serving
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      MODEL_URL: https://storage.googleapis.com/model-serving-fixtures/mobilenet_v1.zip
