version: '3'
services:
  tf-serving:
    build:
      context: docker/test-tf-serving
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SERVING_MODEL: https://s3.amazonaws.com/tf-models-839c7ddd-9cab-49fa-9b42-bde1a842086e/mobilenet_v1.tar.gz
