#!/usr/bin/env bash
set -e
VERSION=$(grep "version=" setup.py | tr -d "version='" | tr -d ",'" | tr -d "[:space:]")
source script/docker_build_and_push.sh
set -x

docker_build_and_push triage/model-serving:$VERSION docker/Dockerfile "--build-arg BASE_TAG=1.15.2"
docker_build_and_push triage/model-serving-gpu:$VERSION docker/Dockerfile "--build-arg BASE_TAG=1.15.2-gpu"
