#!/usr/bin/env bash
set -e
VERSION=$(grep "version=" setup.py | tr -d "version='" | tr -d ",'" | tr -d "[:space:]")
source script/docker_build_and_push.sh
set -x

docker_build_and_push triage/model-serving:$VERSION docker/Dockerfile "--build-arg BASE_IMAGE=python2.7-tensorflow-serving"
docker_build_and_push triage/model-serving-optimized:$VERSION docker/Dockerfile "--build-arg BASE_IMAGE=python2.7-tensorflow-serving-optimized"
docker_build_and_push triage/model-serving-gpu:$VERSION docker/Dockerfile "--build-arg BASE_IMAGE=python2.7-tensorflow-serving-gpu"
docker_build_and_push triage/model-serving-optimized-gpu:$VERSION docker/Dockerfile "--build-arg BASE_IMAGE=python2.7-tensorflow-serving-optimized-gpu"
