#!/usr/bin/env bash
ARGS="${@:-tests/}"
set -e

# Run tests and lint checks.
PYTHONPATH="." pytest --cov=./ -v -s $ARGS
flake8 --max-line-length 50000 --ignore W503,F812 model_serving tests

# Upload coverage for CI.
if [ -n "$CI" ]; then
  pip install codecov
  codecov
fi
