#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Wait until the model-serving connection is up.
n=0
until [ $n -ge 10 ]
do
  if [[ $(nc localhost 9000 -w 1 | wc -c) -ne 0 ]]; then break; fi
  n=$[$n+1]
  sleep 1
done

# Run tests and lint checks.
PYTHONPATH="." pytest --cov=./ $ARGS
flake8 --max-line-length 50000 --ignore W503,F812 model_serving tests

# Upload coverage for CI.
if [ -n "$CI" ]; then
  pip install codecov
  codecov
fi
